export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';

export const NEW_POST_SUCCESS = 'NEW_POSTS_SUCCESS';
export const NEW_POST_REQUEST = 'NEW_POSTS_REQUEST';
export const NEW_POST_FAILURE = 'NEW_POSTS_FAILURE';

export const FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS';
export const FETCH_QUESTIONS_REQUEST = 'FETCH_QUESTIONS_REQUEST';
export const FETCH_QUESTIONS_FAILURE = 'FETCH_QUESTIONS_FAILURE';

export const FETCH_QUESTION_DETAIL_SUCCESS = 'FETCH_QUESTION_DETAIL_SUCCESS';
export const FETCH_QUESTION_DETAIL_REQUEST = 'FETCH_QUESTION_DETAIL_REQUEST';
export const FETCH_QUESTION_DETAIL_FAILURE = 'FETCH_QUESTION_DETAIL_FAILURE';

export const SEND_VOTE_SUCCESS = 'SEND_VOTE_SUCCESS';
export const SEND_VOTE_REQUEST = 'SEND_VOTE_REQUEST';
export const SEND_VOTE_FAILURE = 'SEND_VOTE_FAILURE';

export const SHARE_EMAIL_SUCCESS = 'SHARE_EMAIL_SUCCESS';
export const SHARE_EMAIL_REQUEST = 'SHARE_EMAIL_REQUEST';
export const SHARE_EMAIL_FAILURE = 'SHARE_EMAIL_FAILURE';

export const FETCH_SERVER_HEALTH_SUCCESS = 'FETCH_SERVER_HEALTH_SUCCESS';
export const FETCH_SERVER_HEALTH_REQUEST = 'FETCH_SERVER_HEALTH_REQUEST';
export const FETCH_SERVER_HEALTH_FAILURE = 'FETCH_SERVER_HEALTH_FAILURE';

